about/urls.py
from django.urls import path, include

from about import views

from .views import about

app_name = 'about'

urlpatterns = [
    path('about', views.about, name='about'),
]

contact/urls.py
from django.urls import path, include

#import views
from  contact import views

#import contact view
from  .views import contact

app_name = 'contact'

urlpatterns = [
    path('contact', views.contact, name='contact'),
]

guidance/urls.py
from django.urls import path, include

from guidance import views
from .views import *

app_name = 'guidance'

urlpatterns = [
    path('guidance', views.guidance, name='guidance'),
]

home/urls.py
from django.urls import path

from .views import index
app_name = 'home'

urlpatterns = [
    path('', index, name='index'),
]

project101/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
#for media files import static
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('', include('contact.urls')),
    path('', include('about.urls')),
    path('', include('university.urls')),
    path('', include('guidance.urls'))
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

university/urls.py
from django.urls import path, include

from university import views

from .views import *

app_name = 'university'

urlpatterns = [
    path('university', views.university, name='university'),
]

about/models.py
from django.db import models

# Create your models here.
class About(models.Model):
    title = models.CharField(max_length=225)
    catchy = models.CharField(max_length=400)
    body = models.TextField()
    #thumbnail = models.ImageField(upload_to='')

contact/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField()
    subject = models.CharField(max_length=30)
    message = models.TextField()

    def __str__(self):
        return f"{self.name}, {self.email}, {self.subject}, {self.message}"

guidance/models.py
from django.db import models
from django.contrib.auth import get_user_model

#CREATE global variable user
User = get_user_model()
# Create your models here.

class GuidanceView(models.Model):
    user =models.ForeignKey(User, on_delete=models.CASCADE)
   # post = models.ForeignKey('Post', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username}"

        

home/models.py
from django.db import models

# Create your models here.

university/models.py
from django.db import models

#import reverse for absolute url
from django.urls import reverse

#import file validation module
from .validators import image_validation_extension
#South African Provinces
PROVINCES =(
    ('Northern Cape', 'Northern Cape'),
    ('Eastern Cape', 'Eastern Cape'),
    ('Free State', 'Free State'),
    ('Western Cape', 'Western Cape'),
    ('Limpopo', 'Limpopo'),
    ('North West', 'North West'),
    ('KwaZulu-Natal', 'KwaZulu-Natal'),
    ('Mpumalanga', 'Mpumalanga'),
    ('Gauteng', 'Gauteng')
)
# Create your models here.


class UniversityView(models.Model):
    name = models.CharField(max_length=255)
    logo = models.ImageField(upload_to='university/logo/', validators=[image_validation_extension])
    update = models.DateTimeField(auto_now_add=True)
    province = models.CharField(choices=PROVINCES, max_length=244)
    physical_address = models.TextField()

    def get_absolute_url(self):
        return reverse('university:university.html')

    def __str__(self):
        return f"{self.name}"
class Faculty(models.Model):
    name = models.CharField(max_length=255)
    school_or_department = models.CharField(max_length=255)

class Contact(models.Model):
    tel = models.IntegerField()
    emai = models.EmailField()
    website = models.CharField(max_length=255)
class AdmissionRequirement(models.Model):
    subject = models.CharField(max_length=255)

contact/forms.py
from django import forms
#bringing in the Contact model from models
from .models import Contact

#creating form to accept user information when contacting us
class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email','subject', 'message']
 

about/views.py
from django.shortcuts import render


#import about us model fom models
from .models import About
# Create your views here.

#creating about us view

def about(request):
    context = {
        'about': About.objects.all()
    }

    return render(request, 'about/about.html')

contact/views.py
from django.shortcuts import render

from .models import Contact
# Create your views here.

#creating contact view using function based views

def contact(request):
    context = {
        'contacts': Contact.objects.all()
    }
    return render(request, 'contact/contact.html', context)

guidance/views.py
from django.shortcuts import render

from .models import *
# Create your views here.

def guidance(request):
    context = {
        'university': GuidanceView.objects.all()
    }
    return render(request, 'guidance/guidance.html', context)

home/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'home/index.html')

university/views.py
from django.shortcuts import render

#import University model
from .models import UniversityView
# Create your views here.

def university(request):
    context = {
        'university':UniversityView.objects.all()
    }

    return render(request, 'university/university.html', context)

about/templates/about/about.html
{% extends "home/base.html" %}

{% load static %}
<link rel="stylesheet" href="{% static 'about/css/style.css' %}"/>
{% block content%} 

{% endblock content %}

contact/templates/contact/contact.html
{% extends "home/base.html" %}
{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'contact/css/style.css' %}"/>
<style>
h1{
    text-align:center;
}
</style>

<form action="{% url 'contact:contact' %}" method="POST">
{% csrf_token %}
<br><br>
<h1>Leave Your Question Below.<h1>
{% csrf_token %}
{{form}}
<br/>
      <div class="form-container">
        <form action="#" method="POST">
          <label for="name">Name</label>
          <input type="text" name="name" required="">
          <label for="email" name="email">Email Address</label>
          <input type="text" name="email" required="">
          </br><hr>
    
          <label for="message">Message</label>
          <textarea name="message" cols="30" rows="10" required=""></textarea>
          <input type="submit" value="Send Message" required="">
        </form>
      </div>

{% endblock content %}

guidance/templates/guidance/guidance.html
{% extends "home/base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'guidance/css/style.css' %}"/>

<br>

<br>
<h1>Hello World</h1>
{% endblock content%}

home/templates/home/base.html
{% load static %}


<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Career Guidance</title>

    <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
{% block styles %}
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      /* GLOBAL STYLES
-------------------------------------------------- */
/* Padding below the footer and lighter body text */

body {
  padding-top: 3rem;
  padding-bottom: 3rem;
  color: #5a5a5a;
}


/* CUSTOMIZE THE CAROUSEL
-------------------------------------------------- */

/* Carousel base class */
.carousel {
  margin-bottom: 4rem;
}
/* Since positioning the image, we need to help out the caption */
.carousel-caption {
  bottom: 3rem;
  z-index: 10;
}

/* Declare heights because of positioning of img element */
.carousel-item {
  height: 32rem;
}
.carousel-item > img {
  position: absolute;
  top: 0;
  left: 0;
  min-width: 100%;
  height: 32rem;
}


/* MARKETING CONTENT
-------------------------------------------------- */

/* Center align the text within the three columns below the carousel */
.marketing .col-lg-4 {
  margin-bottom: 1.5rem;
  text-align: center;
}
.marketing h2 {
  font-weight: 400;
}
.marketing .col-lg-4 p {
  margin-right: .75rem;
  margin-left: .75rem;
}


/* Featurettes
------------------------- */

.featurette-divider {
  margin: 5rem 0; /* Space out the Bootstrap <hr> more */
}

/* Thin out the marketing headings */
.featurette-heading {
  font-weight: 300;
  line-height: 1;
  letter-spacing: -.05rem;
}


/* RESPONSIVE CSS
-------------------------------------------------- */

@media (min-width: 40em) {
  /* Bump up size of carousel content */
  .carousel-caption p {
    margin-bottom: 1.25rem;
    font-size: 1.25rem;
    line-height: 1.4;
  }

  .featurette-heading {
    font-size: 50px;
  }
}

@media (min-width: 62em) {
  .featurette-heading {
    margin-top: 7rem;
  }
}
.navbar-expand-md{
  background-color: #0066CC !important;
}
.btn-search{
  background-color: #3399ff !important;
  color: white;
}
    </style>
    {% endblock styles %}
  </head>
  <body>
    <header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="/">Project 101</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#"> <span class="sr-only">(current)</span></a>
        </li>
       
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'guidance:guidance' %}">Career Guidance</a>
        </li>
         <li class="nav-item active">
          <a class="nav-link" href="{% url 'university:university' %}">Find University | College</a>
        </li>
      </ul>
      <form class="form-inline mt-2 mt-md-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-search my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
</header>
{% block content %}{% endblock content %}
{%block footer %}
 <!-- FOOTER -->
  <footer class="container">
    <li class="nav-item active">
          <a class="nav-link" href="{% url 'about:about' %}">About Us</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'contact:contact' %}">Contact Us</a>
        </li>
    <p class="float-right"><a href="#">Back to top</a></p>
    <p>&copy; 2019 Project 101 Initiative. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
  </footer>
{% endblock footer %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

home/templates/home/index.html
{% extends "home/base.html" %}

{% block content %}

<main role="main">

  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img"><rect width="100%" height="100%" fill="#777"/></svg>
        <div class="container">
          <div class="carousel-caption text-left">
            <h1>University Admission.</h1>
            <p>Find out the minimum requiremnts for university admission to ICT and Computer Science Field.</p>
            <p><a class="btn btn-lg btn-primary" href="#" role="button">Find out!</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img"><rect width="100%" height="100%" fill="#777"/></svg>
        <div class="container">
          <div class="carousel-caption">
            <h1>Career Opportunities Within ICT and Computer Science Field.</h1>
            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
            <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img"><rect width="100%" height="100%" fill="#777"/></svg>
        <div class="container">
          <div class="carousel-caption text-right">
            <h1>Find The Best Univesity To Start Your Career!</h1>
            <p>South African universities are amongst the best in the world. Browse through the list and apply. We wish you all the best of luck!.</p>
            <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
          </div>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>


  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->

  <div class="container marketing">

    <!-- Three columns of text below the carousel -->
    <div class="row">
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 140x140"><title>Placeholder</title><rect width="100%" height="100%" fill="#cc0000"/><text x="50%" y="50%" fill="#cc0000" dy=".3em">140x140</text></svg>
        <h2>Heading</h2>
        <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
        <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 140x140"><title>Placeholder</title><rect width="100%" height="100%" fill="#ffcc66"/><text x="50%" y="50%" fill="#ffcc66" dy=".3em">140x140</text></svg>
        <h2>Heading</h2>
        <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
        <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 140x140"><title>Placeholder</title><rect width="100%" height="100%" fill="#996699"/><text x="50%" y="50%" fill="#996699" dy=".3em">140x140</text></svg>
        <h2>Heading</h2>
        <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->


    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It’ll blow your mind.</span></h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
      </div>
      <div class="col-md-5">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 500x500"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading">Oh yeah, it’s that good. <span class="text-muted">See for yourself.</span></h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
      </div>
      <div class="col-md-5 order-md-1">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 500x500"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
      </div>
      <div class="col-md-5">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 500x500"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>
      </div>
    </div>

    <hr class="featurette-divider">

    <!-- /END THE FEATURETTES -->

  </div><!-- /.container -->
</main>
{% endblock content %}

university/templates/university/university.html
{% extends "home/base.html" %}

{% load static %}
<link rel="stylesheet" href="{% static 'university/css/style.css' %}"/>
{% block content %}
 <section class="section-bg">
      <div class="container">
        <header class="section-header">
          <h1>South African Universities</h1>
          <p>Choose the best institution to quick start your careers.</p>
          <p></p>
        </header>
        <div class="flex wrap skills">
        {% for u in university %}
          <div class="card">
            <img src="{{ u.logo.url }}" alt="">
            <h2>{{ u.name}}</h2>
          </div>
          {% endfor %}
        </div>
      </div>

    </section>
{% endblock content %}